"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "it" | "en" | "es";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const translations = {
  "it": {
    "nav.home": "Home",
    "nav.about": "Su di Me",
    "nav.services": "Servizi",
    "nav.portfolio": "Prima e Dopo",
    "nav.blog": "Blog",
    "nav.faq": "FAQ",
    "nav.bookNow": "Prenota Ora",
    "nav.selectLang": "Seleziona Lingua",
    "nav.lang_it": "Italiano",
    "nav.lang_en": "English",
    "nav.lang_es": "Español",
    "hero.loading": "Caricamento esperienza...",
    "hero.title1": "L'arte della manicure",
    "hero.title2": "su misura per te",
    "hero.desc": "Un'esperienza di bellezza per valorizzare la tua femminilità. Ogni dettaglio è studiato per creare armonia, eleganza e personalità.",
    "hero.bookBtn": "Prenota Ora",
    "hero.servicesBtn": "Scopri i Servizi",
    "intro.badge": "Chi Siamo",
    "intro.heading": "Un ambiente intimo e raffinato",
    "intro.p1": "Qui non è solo un appuntamento: è un momento di relax e benessere dedicato a te. Beauty Dreamer nasce dall'idea di offrire un nuovo concetto di nail care: non solo estetica, ma valorizzazione della persona.",
    "intro.p2": "Perché mani curate non sono solo un dettaglio, ma un segno distintivo di stile.",
    "intro.myStory": "La mia storia",
    "vieni.title": "Vieni a",
    "vieni.titleAccent": "trovarci",
    "vieni.desc": "Vieni a trovarci, operiamo a Milano City-life. Un ambiente pensato per farti rilassare, dove la cura di te stessa diventa un rito di bellezza.",
    "vieni.cta": "Fissa un appuntamento",
    "srvPrev.badge": "I Nostri Trattamenti",
    "srvPrev.heading": "Prenditi cura di te",
    "srvPrev.manicureTitle": "Manicure & Pedicure",
    "srvPrev.manicureDesc": "Trattamenti curativi a secco o spa per mani e piedi impeccabili.",
    "srvPrev.ricostruzioneTitle": "Ricostruzione",
    "srvPrev.ricostruzioneDesc": "Gel, Acrygel o Acrilico per allungamenti naturali o estremi.",
    "srvPrev.nailArtTitle": "Nail Art",
    "srvPrev.nailArtDesc": "Dal french al babyboomer, dettagli personalizzati per uno stile unico.",
    "srvPrev.allServicesBtn": "Vedi il Listino Completo",
    "testimonials.quote": "Con anni d'esperienza nel settore della bellezza ed una passione innata per l'eccellenza, Chiara ti accoglierà in un ambiente accogliente e raffinato, dove la tua bellezza ed il tuo benessere sono di primaria importanza.",
    "testimonials.author": "Le Nostre Clienti",
    "ig.openTitle": "Aprire Instagram?",
    "ig.openDesc": "Vuoi visualizzare il profilo ufficiale di @beautydreameraesthetic per scoprire tutti i lavori e le novità?",
    "ig.openBtn": "Apri Profilo",
    "ig.stayBtn": "Rimani sul Sito",
    "ig.follow": "Segui",
    "ig.caption": "L'arte della manicure a Milano City-Life. Dedizione, eleganza e cura in ogni dettaglio ✨💅",
    "ig.audio": "Audio originale • Chiara Lulli • Beauty Dreamer",
    "ig.soundOn": "Attiva Audio",
    "ig.soundOff": "Disattiva Audio",
    "about.badge": "La mia storia",
    "about.p1": "Mi chiamo Chiara, estetista specializzata ed onicotecnica.",
    "about.p2": "Fin da piccola ho maturato la passione per l'estetica. Attratta da trucchi, smalti e mani curate, ho deciso dopo qualche anno di intraprendere il mio viaggio, verso quello che da sempre è stato il mio sogno.",
    "about.p3": "Ho studiato per potermi specializzare in estetista, make-up ed onicotecnica, ho frequentato corsi di perfezionamento nell'ambito della ricostruzione unghie e di tutto ciò che ne consegue. Oggi, ho finalmente raggiunto il mio obiettivo, pronta a trasformare quello che da sempre ho desiderato, in una passione.",
    "about.quote": "Dedizione e amore, sono due elementi importanti per rendere unico il mio lavoro, gratificandomi ogni giorno di più.",
    "about.cta": "Scopri i miei servizi",
    "about.welcomeBadge": "Benvenuti in",
    "about.welcomeHeading": "Beauty Dreamer",
    "about.welcomeP1": "Il rifugio perfetto per l'arte della manicure e pedicure, curato personalmente da Chiara Lulli. Presso il nostro Nail Concept, ci impegnano a offrire trattamenti dedicati e personalizzati per soddisfare le esigenze uniche di ogni cliente.",
    "about.welcomeP2": "La nostra missione è rendere ogni visita un'esperienza rilassante, rigenerante e soprattutto bella.",
    "about.welcomeP3": "Scegli Beauty Dreamer per il tuo prossimo trattamento e lasciati trasportare in un mondo di colori e bellezza senza tempo.",
    "services.headerTitle": "I Nostri Trattamenti",
    "services.headerSubtitle": "Scopri il listino completo dei servizi offerti da BeautyDreamer. Prenota il tuo momento di relax.",
    "services.bookService": "Prenota questo servizio",
    "services.cat1": "Manicure & Pedicure",
    "services.s1_1_title": "Dry Manicure",
    "services.s1_1_desc": "Trattamento di manicure a secco, per lavorare perfettamente il giro cuticola e per permettere la massima adesione di ogni prodotto applicato.",
    "services.s1_1_price": "da 20€",
    "services.s1_2_title": "Pedicure Senza Lame",
    "services.s1_2_desc": "Pedicure estetico e curativo, eseguito con massima professionalità senza lame.",
    "services.s1_2_price": "da 35€",
    "services.cat2": "Semipermanente",
    "services.s2_1_title": "Mani o Piedi",
    "services.s2_1_desc": "Semipermanente classico o rinforzato per una durata maggiore.",
    "services.s2_1_price": "da 30€",
    "services.cat3": "Ricostruzione & Ritocco",
    "services.s3_1_title": "Ricostruzione Gel / Acrygel / Acrilico",
    "services.s3_1_desc": "Ricostruzione corta - media - lunga - estrema - onicofagica.",
    "services.s3_1_price": "da 60€",
    "services.s3_2_title": "Ritocco Gel / Acrygel / Acrilico",
    "services.s3_2_desc": "Refill mensile 3/4 settimane.",
    "services.s3_2_price": "da 45€",
    "services.s3_3_title": "Copertura su Unghia Naturale",
    "services.s3_3_desc": "Eseguita per la prima volta su unghia naturale con Gel, Acrygel o Acrilico.",
    "services.s3_3_price": "da 45€",
    "services.cat4": "Nail Art",
    "services.s4_1_title": "In aggiunta al trattamento",
    "services.s4_1_desc": "French disegnato, babyboomer, disegni vari, applicazioni Swarovski, foil, polveri.",
    "services.s4_1_price": "da 5€",
    "services.cat5": "Trattamenti Mani / Piedi",
    "services.s5_1_title": "Gel Break",
    "services.s5_1_desc": "Trattamento per il recupero dell'unghia.",
    "services.s5_1_price": "da 15€",
    "services.s5_2_title": "Anti Dark Spot",
    "services.s5_2_desc": "Trattamento anti macchia per pelli mature o segnate.",
    "services.s5_2_price": "da 20€",
    "services.s5_3_title": "Manicure / Pedicure Spa",
    "services.s5_3_desc": "Esfoliazione, idratazione profonda e massaggio rilassante.",
    "services.s5_3_price": "da 30€",
    "services.s5_4_title": "Calluspeeling",
    "services.s5_4_desc": "Trattamento levigante specifico per callosità dei piedi.",
    "services.s5_4_price": "da 35€",
    "services.cat6": "Epilazione",
    "services.s6_1_title": "Ceretta Senza Strappo (Donna/Uomo)",
    "services.s6_1_desc": "Epilazione ultra-delicata specifica per pelli sensibili.",
    "services.s6_1_price": "da 10€",
    "portfolio.title": "Prima e Dopo",
    "portfolio.subtitle": "Scopri i risultati dei nostri trattamenti. Una galleria dedicata ai lavori di Chiara Lulli.",
    "portfolio.tabAll": "Tutti",
    "portfolio.tabRicostruzione": "Ricostruzione",
    "portfolio.tabNailArt": "Nail Art",
    "portfolio.tabPrimaDopo": "Prima e Dopo",
    "portfolio.bookResult": "Prenota questo risultato",
    "portfolio.swipeTip": "Scorri i video per vedere le trasformazioni",
    "blog.title": "Blog & Consigli di Bellezza",
    "blog.subtitle": "Guide, approfondimenti e segreti professionali per la cura e la salute delle tue unghie, firmati da Chiara Lulli.",
    "blog.allArticles": "Tutti gli Articoli",
    "blog.readTime": "tempo di lettura",
    "blog.readArticle": "Leggi Articolo Completo",
    "blog.readingModalTitle": "Approfondimento Esclusivo",
    "blog.authorBy": "A cura di Chiara Lulli",
    "blog.proTipTitle": "Il Consiglio Pro di Chiara",
    "blog.shareWhatsApp": "Condividi su WhatsApp",
    "blog.bookAfterReading": "Prenota un Trattamento",
    "blog.backToBlog": "Torna al Blog",
    "blog.a1_title": "Come mantenere il semipermanente perfetto a lungo",
    "blog.a1_excerpt": "Piccoli segreti quotidiani e abitudini da evitare per far durare il tuo smalto fino a 4 settimane senza sbeccature.",
    "blog.a1_category": "Cura delle Unghie",
    "blog.a1_date": "10 Settembre 2026",
    "blog.a1_intro": "Il semipermanente è la soluzione ideale per avere unghie impeccabili e brillanti per settimane. Tuttavia, la durata del trattamento dipende anche dalla routine di cura quotidiana a casa. Ecco i consigli professionali di Chiara per massimizzare la resa del tuo smalto.",
    "blog.a1_h1": "1. Proteggi le mani con i guanti",
    "blog.a1_t1": "Detersivi, sgrassatori e prodotti chimici aggressivi possono intaccare il sigillante lucido e causare sollevamenti precoci. Indossa sempre guanti di gomma quando lavi i piatti o ti dedichi alle pulizie domestiche.",
    "blog.a1_h2": "2. Idratazione quotidiana delle cuticole",
    "blog.a1_t2": "Applicare una goccia di olio nutriente ogni sera prima di dormire mantiene la lamina flessibile ed elastica, prevenendo le rotture e mantenendo il giro cuticola ordinato come appena uscite dalla seduta.",
    "blog.a1_h3": "3. Non usare le unghie come attrezzi",
    "blog.a1_t3": "Evita di fare leva per aprire lattine, pacchi o graffiare superfici: piccoli urti ripetuti sulla punta creano micro-fratture invisibili che portano a scheggiature.",
    "blog.a1_conclusion": "Seguendo questi accorgimenti, il tuo semipermanente rimarrà brillante e sigillato fino al prossimo refill!",
    "blog.a1_proTip": "Se noti un piccolo sollevamento, non strapparlo mai: fissa subito un appuntamento per una riparazione rapida senza rovinare l'unghia naturale.",
    "blog.a2_title": "Trend Nail Art Autunno / Inverno",
    "blog.a2_excerpt": "Scopri i colori e le texture di tendenza. Dai toni bordeaux intensi al nude sofisticato, fino al ritorno del minimalismo chic.",
    "blog.a2_category": "Trend & Stile",
    "blog.a2_date": "2 Settembre 2026",
    "blog.a2_intro": "La nuova stagione celebra l'eleganza raffinata con dettagli sartoriali. Tra sfumature calde e accenti luminosi, le mani diventano un vero e proprio accessorio di stile.",
    "blog.a2_h1": "Bordeaux Profondo & Cherry Mocha",
    "blog.a2_t1": "I toni vino, bordeaux e amarena scuro dominano le richieste: classici, senza tempo e perfetti sia su unghie corte squadrate che su forme a mandorla.",
    "blog.a2_h2": "Micro French & Dettagli Dorati",
    "blog.a2_t2": "La classica french manicure si rinnova con linee sottilissime e tocchi di polvere dorata o cromata su basi nude lattiginose.",
    "blog.a2_h3": "Effetto Vetro & Babyboomer Soft",
    "blog.a2_t3": "La sfumatura degradé naturale dal bianco latte al rosa carne dona un aspetto curato, pulito e luminoso adatto a qualsiasi occasione.",
    "blog.a2_conclusion": "Vieni a trovarci a Milano City-Life per personalizzare la tua Nail Art secondo la forma naturale delle tue mani.",
    "blog.a2_proTip": "Le finiture glossy con top coat a specchio valorizzano al massimo i colori scuri autunnali.",
    "blog.a3_title": "Olio per Cuticole: perché non puoi farne a meno",
    "blog.a3_excerpt": "L'idratazione è la chiave per una manicure che duri nel tempo. Ecco perché l'olio per cuticole deve diventare il tuo alleato quotidiano.",
    "blog.a3_category": "Skincare Mani",
    "blog.a3_date": "20 Agosto 2026",
    "blog.a3_intro": "Spesso sottovalutato, l'olio per cuticole è in realtà il segreto numero uno per mani sempre morbide, sane e dall'aspetto professionale anche a distanza di giorni dalla manicure.",
    "blog.a3_h1": "Nutrimento in profondità",
    "blog.a3_t1": "A differenza delle creme mani che agiscono solo in superficie, gli oli vegetali puri (come jojoba, mandorle dolci e vitamina E) penetrano nella matrice dell'unghia stimolandone una crescita forte e sana.",
    "blog.a3_h2": "Prevenzione delle pellicine",
    "blog.a3_t2": "Un'applicazione costante ammorbidisce le cuticole, evitando che si secchino o si sollevino creando fastidiose irritazioni o micro-tagli.",
    "blog.a3_h3": "Maggiore durata dei trattamenti",
    "blog.a3_t3": "Un'unghia elastica ed idratata assorbe meglio gli urti e crea un legame più flessibile e duraturo con le basi in gel e semipermanente.",
    "blog.a3_conclusion": "Bastano 30 secondi al giorno per trasformare radicalmente la salute e l'aspetto delle tue mani.",
    "blog.a3_proTip": "Massaggia l'olio compiendo movimenti circolari su tutta la cuticola e fino alla prima falange per riattivare la microcircolazione.",
    "faq.title": "Domande Frequenti",
    "faq.subtitle": "Hai dubbi o curiosità sui trattamenti? Qui trovi le risposte chiare a tutte le domande più comuni.",
    "faq.q1": "Quanto dura il semipermanente?",
    "faq.a1": "Il semipermanente classico ha una durata media di 2-3 settimane. Optando per un semipermanente rinforzato con base rubber o struttura, la durata può estendersi fino a 4 settimane, garantendo maggiore resistenza, lucentezza e protezione all'unghia naturale.",
    "faq.q2": "Come posso rimuovere il semipermanente o la ricostruzione in sicurezza?",
    "faq.a2": "È fondamentale non rimuovere mai i prodotti da sola strappandoli o raschiandoli, per evitare di assottigliare e danneggiare la lamina ungueale. Offriamo un servizio di rimozione professionale e curativa con punte fresa calibrate che preserva la salute delle tue unghie.",
    "faq.q3": "Quali standard igienici seguite?",
    "faq.a3": "La sicurezza e l'igiene sono la nostra priorità assoluta. Utilizziamo lime e materiali monouso per ogni cliente. Tutti gli attrezzi in acciaio chirurgico vengono rigorosamente decontaminati, detersi, disinfettati e sterilizzati in autoclave imbustati singolarmente.",
    "faq.q4": "Qual è la politica di cancellazione o ritardo?",
    "faq.a4": "Ti chiediamo gentilmente di disdire o spostare il tuo appuntamento con almeno 24 ore di preavviso per permetterci di riorganizzare l'agenda. In caso di ritardo superiore a 15 minuti, il trattamento potrebbe essere rimodulato per rispettare gli appuntamenti successivi.",
    "faq.q5": "La ricostruzione unghie rovina l'unghia naturale?",
    "faq.a5": "Assolutamente no. Se eseguita correttamente da un'operatrice qualificata e con prodotti professionali certificati di alta qualità, la ricostruzione non danneggia l'unghia naturale. Anzi, protegge l'unghia ed è ideale per superare l'onicofagia (unghie mangiate).",
    "faq.q6": "Posso portare un design da replicare per la Nail Art?",
    "faq.a6": "Certamente! Puoi inviarmi la foto di ispirazione direttamente su WhatsApp prima dell'appuntamento o mostrarmela in studio. Realizziamo decorazioni personalizzate a mano libera, babyboomer, french e dettagli con polveri e cristalli.",
    "book.title": "Prenota il tuo Trattamento",
    "book.subtitle": "Compila il modulo sottostante per richiedere il tuo appuntamento. Riceverai una conferma rapida su WhatsApp.",
    "book.progress": "Compilazione modulo",
    "book.step1": "1. Seleziona il Trattamento",
    "book.selectServicePlaceholder": "-- Scegli un Trattamento --",
    "book.step2": "2. Data e Orario Desiderati",
    "book.dateLabel": "Data Preferita",
    "book.timeLabel": "Fascia Oraria",
    "book.selectTimePlaceholder": "-- Scegli la fascia oraria --",
    "book.timeMorning": "Mattina (09:30 - 13:00)",
    "book.timeAfternoon": "Pomeriggio (14:30 - 19:30)",
    "book.step3": "3. I Tuoi Recapiti",
    "book.firstName": "Nome",
    "book.lastName": "Cognome",
    "book.email": "Email",
    "book.phone": "Cellulare (WhatsApp)",
    "book.notes": "Note o Richieste Particolari (opzionale)",
    "book.notesPlaceholder": "Es. 'Vorrei una nail art personalizzata', 'Ho unghie fragili', ecc.",
    "book.step4": "4. Opzioni Aggiuntive",
    "book.optWhatsapp": "Desidero ricevere il promemoria automatico dell'appuntamento su WhatsApp.",
    "book.optRemoval": "Ho già uno smalto/gel da rimuovere applicato da un altro centro (+15 min).",
    "book.submitBtn": "Invia Richiesta di Prenotazione",
    "book.badge1Title": "Conferma Rapida",
    "book.badge1Desc": "Risposta e riepilogo su WhatsApp entro poche ore.",
    "book.badge2Title": "Igiene Certificata",
    "book.badge2Desc": "Strumenti sterilizzati in autoclave e monouso.",
    "book.badge3Title": "Location Esclusiva",
    "book.badge3Desc": "Studio accogliente a Milano City-Life.",
    "book.successTitle": "Richiesta Inviata con Successo!",
    "book.successDesc": "Grazie per aver scelto BeautyDreamer. Abbiamo registrato la tua richiesta e ti contatteremo a breve su WhatsApp per la conferma definitiva.",
    "book.summaryTitle": "Riepilogo della tua richiesta:",
    "book.summaryTreatment": "Trattamento:",
    "book.summaryDate": "Data:",
    "book.summaryTime": "Orario:",
    "book.summaryClient": "Cliente:",
    "book.summaryPhone": "Telefono:",
    "book.summaryLocation": "Indirizzo:",
    "book.addToGoogleCal": "Aggiungi a Google Calendar",
    "book.downloadIcs": "Scarica Promemoria (.ics / Apple)",
    "book.shareWhatsApp": "Invia Promemoria su WhatsApp",
    "book.backHome": "Torna alla Home",
    "footer.tagline": "Un'esperienza di bellezza per valorizzare la tua femminilità.",
    "footer.quickLinks": "Link Rapidi",
    "footer.contacts": "Contatti",
    "footer.legalInfo": "Info Legali",
    "footer.rights": "Tutti i diritti riservati.",
    "services.promoBannerTitle": "Offerte Speciali, Combo & Gift Card",
    "services.promoBannerSubtitle": "Approfitta delle promozioni attive, abbina più trattamenti per sbloccare sconti bundle esclusivi oppure utilizza voucher e gift card per il tuo momento di bellezza.",
    "services.copyCode": "Copia Codice",
    "services.copiedCode": "Copiato!",
    "services.bookWithPromo": "Prenota con questa Promo",
    "services.p_dry_badge": "COMBO PROMO -15%",
    "services.p_dry_title": "Combo Mani + Piedi Perfetti",
    "services.p_dry_desc": "Combina con Pedicure Senza Lame e ricevi il 15% di sconto sul totale + idratazione cuticole in omaggio.",
    "services.p_dry_code": "COMBOMANIPIEDI",
    "services.p_semi_badge": "PROMO PACK 3 SEDUTE",
    "services.p_semi_title": "Abbonamento Semipermanente",
    "services.p_semi_desc": "Carnet 3 sedute con 1 Nail Art omaggio inclusa ad ogni seduta. Risparmia subito inserendo il voucher.",
    "services.p_semi_code": "SEMIPACK",
    "services.p_ricostruzione_badge": "VOUCHER SCONTO -10%",
    "services.p_ricostruzione_title": "Welcome Promo Nuova Ricostruzione",
    "services.p_ricostruzione_desc": "10% di sconto riservato alla tua prima ricostruzione completa unghie (Gel, Acrygel o Acrilico).",
    "services.p_ricostruzione_code": "NEWBEAUTY",
    "services.p_spa_badge": "GIFT CARD & VOUCHER",
    "services.p_spa_title": "Esperienza Spa o Gift Card Regalo",
    "services.p_spa_desc": "Regala o concediti un rituale di bellezza e relax profondo. Disponibile anche come elegante Gift Card.",
    "services.p_spa_code": "GIFTDREAM",
    "services.p_callus_badge": "COMBO WELLNESS",
    "services.p_callus_title": "Combo Levigante + Pedicure Spa",
    "services.p_callus_desc": "Abbina Calluspeeling e Pedicure Spa a soli 55€ (invece di 65€) per piedi completamente rinnovati.",
    "services.p_callus_code": "PEDISPA55",
    "book.voucherLabel": "Codice Promo, Voucher o Gift Card (Opzionale)",
    "book.voucherPlaceholder": "Es. COMBOMANIPIEDI, BEAUTY10, SEMIPACK...",
    "book.voucherApply": "Applica",
    "book.voucherApplied": "Promo applicata con successo!",
    "book.voucherInvalid": "Codice promo o voucher non valido",
    "book.summaryVoucher": "Voucher / Promo:"
  },
  "en": {
    "nav.home": "Home",
    "nav.about": "About Me",
    "nav.services": "Services",
    "nav.portfolio": "Before & After",
    "nav.blog": "Blog",
    "nav.faq": "FAQ",
    "nav.bookNow": "Book Now",
    "nav.selectLang": "Select Language",
    "nav.lang_it": "Italiano",
    "nav.lang_en": "English",
    "nav.lang_es": "Español",
    "hero.loading": "Loading experience...",
    "hero.title1": "The art of manicure",
    "hero.title2": "tailored for you",
    "hero.desc": "A luxury beauty experience designed to elevate your femininity. Every detail is crafted for harmony, elegance, and distinct personal style.",
    "hero.bookBtn": "Book Now",
    "hero.servicesBtn": "Discover Services",
    "intro.badge": "About Us",
    "intro.heading": "An intimate and refined atmosphere",
    "intro.p1": "Here, it is never just an appointment: it is a dedicated ritual of relaxation and well-being. Beauty Dreamer was born to offer a new vision of nail care: going beyond aesthetics to truly enhance your individuality.",
    "intro.p2": "Because immaculate hands are not merely a detail, but a signature mark of style.",
    "intro.myStory": "My story",
    "vieni.title": "Come and",
    "vieni.titleAccent": "visit us",
    "vieni.desc": "Come visit us in Milan City-Life. An atmosphere designed for complete relaxation, where self-care transforms into a cherished beauty ritual.",
    "vieni.cta": "Book an appointment",
    "srvPrev.badge": "Our Treatments",
    "srvPrev.heading": "Take care of yourself",
    "srvPrev.manicureTitle": "Manicure & Pedicure",
    "srvPrev.manicureDesc": "Dry restorative treatments or luxury spa rituals for flawless hands and feet.",
    "srvPrev.ricostruzioneTitle": "Reconstruction",
    "srvPrev.ricostruzioneDesc": "Gel, Acrygel, or Acrylic for natural extensions or striking lengths.",
    "srvPrev.nailArtTitle": "Nail Art",
    "srvPrev.nailArtDesc": "From micro-french to babyboomer, bespoke hand-painted artistic details.",
    "srvPrev.allServicesBtn": "View Full Price List",
    "testimonials.quote": "With years of dedication in the beauty industry and an innate passion for perfection, Chiara welcomes you into an intimate and refined haven where your beauty and well-being are paramount.",
    "testimonials.author": "Our Clients",
    "ig.openTitle": "Open Instagram?",
    "ig.openDesc": "Would you like to view the official profile of @beautydreameraesthetic to explore our latest designs and updates?",
    "ig.openBtn": "Open Profile",
    "ig.stayBtn": "Stay on Site",
    "ig.follow": "Follow",
    "ig.caption": "The art of manicure in Milan City-Life. Dedication, elegance, and meticulous care in every single detail ✨💅",
    "ig.audio": "Original audio • Chiara Lulli • Beauty Dreamer",
    "ig.soundOn": "Unmute Audio",
    "ig.soundOff": "Mute Audio",
    "about.badge": "My Story",
    "about.p1": "My name is Chiara, specialized esthetician and certified master nail technician.",
    "about.p2": "From a very young age, I cultivated an innate passion for aesthetics. Fascinated by makeup, delicate shades of polish, and pristine hands, I decided to embark on the journey toward what has always been my true calling.",
    "about.p3": "I completed rigorous professional training in beauty therapy, specialized makeup, and advanced nail artistry, attending masterclasses in structural nail reconstruction and restorative techniques. Today, I have fulfilled my dream, transforming my lifelong devotion into everyday artistic excellence.",
    "about.quote": "Dedication and love are the essential pillars that make my craft unique, bringing joy and fulfillment every single day.",
    "about.cta": "Discover my services",
    "about.welcomeBadge": "Welcome to",
    "about.welcomeHeading": "Beauty Dreamer",
    "about.welcomeP1": "The ultimate sanctuary for luxury manicure and pedicure artistry, personally curated by Chiara Lulli. At our Nail Concept studio, we are dedicated to bespoke treatments tailored precisely to each client's unique hands.",
    "about.welcomeP2": "Our mission is to ensure every visit is a deeply relaxing, restorative, and inspiring experience.",
    "about.welcomeP3": "Choose Beauty Dreamer for your next treatment and let yourself be embraced by a world of timeless beauty and effortless elegance.",
    "services.headerTitle": "Our Treatments",
    "services.headerSubtitle": "Discover the full price list of services offered by BeautyDreamer. Book your personal moment of relaxation.",
    "services.bookService": "Book this service",
    "services.cat1": "Manicure & Pedicure",
    "services.s1_1_title": "Dry Manicure",
    "services.s1_1_desc": "Waterless Russian manicure technique for pristine cuticle care and maximum product adhesion.",
    "services.s1_1_price": "from €20",
    "services.s1_2_title": "Bladeless Pedicure",
    "services.s1_2_desc": "Aesthetic and restorative pedicure performed with utmost gentle precision without blades.",
    "services.s1_2_price": "from €35",
    "services.cat2": "Semi-Permanent Gel Polish",
    "services.s2_1_title": "Hands or Feet",
    "services.s2_1_desc": "Classic or rubber-base reinforced gel polish for enhanced strength and long-lasting shine.",
    "services.s2_1_price": "from €30",
    "services.cat3": "Reconstruction & Refill",
    "services.s3_1_title": "Gel / Acrygel / Acrylic Reconstruction",
    "services.s3_1_desc": "Short, medium, long, extreme lengths or onychophagia corrective reconstruction.",
    "services.s3_1_price": "from €60",
    "services.s3_2_title": "Gel / Acrygel / Acrylic Refill",
    "services.s3_2_desc": "Monthly maintenance refill (3 to 4 weeks).",
    "services.s3_2_price": "from €45",
    "services.s3_3_title": "Natural Nail Overlay",
    "services.s3_3_desc": "Reinforcing natural nails with high-resistance Gel, Acrygel, or Acrylic.",
    "services.s3_3_price": "from €45",
    "services.cat4": "Nail Art",
    "services.s4_1_title": "Add-on to Treatment",
    "services.s4_1_desc": "Hand-painted French, babyboomer, custom illustrations, Swarovski crystals, chrome powders.",
    "services.s4_1_price": "from €5",
    "services.cat5": "Hand & Foot Wellness Treatments",
    "services.s5_1_title": "Gel Break",
    "services.s5_1_desc": "Intensive nail restorative and strengthening treatment.",
    "services.s5_1_price": "from €15",
    "services.s5_2_title": "Anti Dark Spot",
    "services.s5_2_desc": "Targeted brightening treatment for sun-exposed or mature skin on hands.",
    "services.s5_2_price": "from €20",
    "services.s5_3_title": "Spa Manicure / Pedicure",
    "services.s5_3_desc": "Exfoliation, deep hydration mask, and relaxing massage.",
    "services.s5_3_price": "from €30",
    "services.s5_4_title": "Calluspeeling",
    "services.s5_4_desc": "Professional softening and smoothing treatment for foot calluses.",
    "services.s5_4_price": "from €35",
    "services.cat6": "Gentle Epilation",
    "services.s6_1_title": "Stripless Wax (Women/Men)",
    "services.s6_1_desc": "Ultra-gentle warm wax formulated specifically for sensitive skin.",
    "services.s6_1_price": "from €10",
    "portfolio.title": "Before & After",
    "portfolio.subtitle": "Explore the transformation results of our treatments. A curated gallery of Chiara Lulli's work.",
    "portfolio.tabAll": "All",
    "portfolio.tabRicostruzione": "Reconstruction",
    "portfolio.tabNailArt": "Nail Art",
    "portfolio.tabPrimaDopo": "Before & After",
    "portfolio.bookResult": "Book this result",
    "portfolio.swipeTip": "Swipe or click arrows to explore transformation videos",
    "blog.title": "Blog & Beauty Secrets",
    "blog.subtitle": "Guides, insights, and professional tips for nail wellness and elevated beauty, curated by Chiara Lulli.",
    "blog.allArticles": "All Articles",
    "blog.readTime": "read time",
    "blog.readArticle": "Read Full Article",
    "blog.readingModalTitle": "Exclusive Deep-Dive",
    "blog.authorBy": "Curated by Chiara Lulli",
    "blog.proTipTitle": "Chiara's Pro Tip",
    "blog.shareWhatsApp": "Share on WhatsApp",
    "blog.bookAfterReading": "Book a Treatment",
    "blog.backToBlog": "Back to Blog",
    "blog.a1_title": "How to keep your gel polish flawless for weeks",
    "blog.a1_excerpt": "Daily secrets and habits to avoid in order to maintain your polish chip-free for up to 4 weeks.",
    "blog.a1_category": "Nail Care",
    "blog.a1_date": "September 10, 2026",
    "blog.a1_intro": "Gel polish is the perfect solution for long-lasting, glossy nails. However, its longevity also depends on your daily at-home care routine. Here are Chiara's expert tips to maximize your manicure's longevity.",
    "blog.a1_h1": "1. Protect your hands with gloves",
    "blog.a1_t1": "Household cleaners, degreasers, and harsh chemicals can erode the glossy topcoat and cause early lifting. Always wear rubber gloves when washing dishes or doing housework.",
    "blog.a1_h2": "2. Daily cuticle hydration",
    "blog.a1_t2": "Applying a drop of nourishing oil every night before bed keeps the nail plate flexible and elastic, preventing breakage and keeping cuticles salon-fresh.",
    "blog.a1_h3": "3. Do not use your nails as tools",
    "blog.a1_t3": "Avoid using your nails to pry open cans, peel stickers, or scratch hard surfaces. Repeated micro-impacts cause invisible stress fractures that lead to chipping.",
    "blog.a1_conclusion": "By following these simple habits, your manicure will remain radiant and intact right up to your next appointment!",
    "blog.a1_proTip": "If you ever notice a slight edge lifting, never peel it off yourself: book a quick touch-up to prevent damaging your natural nail layers.",
    "blog.a2_title": "Autumn / Winter Nail Art Trends",
    "blog.a2_excerpt": "Discover trending colors and textures: from deep cherry mocha and velvet bordeaux to sophisticated minimalist chrome.",
    "blog.a2_category": "Trends & Style",
    "blog.a2_date": "September 2, 2026",
    "blog.a2_intro": "The new season embraces understated luxury with bespoke details. Between rich warm tones and luminous accents, hands become a true statement of style.",
    "blog.a2_h1": "Deep Bordeaux & Cherry Mocha",
    "blog.a2_t1": "Wine tones, deep bordeaux, and dark black-cherry are leading client favorites: timeless, elegant, and flattering on both short square and almond silhouettes.",
    "blog.a2_h2": "Micro French & Gilded Touches",
    "blog.a2_t2": "The classic French manicure gets reinvented with ultra-thin precision smile lines and subtle gold or chrome accents on milky nude bases.",
    "blog.a2_h3": "Glass Finish & Soft Babyboomer",
    "blog.a2_t3": "The natural ombré transition from milky white to soft blush delivers a clean, polished, and luminous aesthetic suitable for every occasion.",
    "blog.a2_conclusion": "Visit us in Milan City-Life to customize your Nail Art to complement your hand's natural elegance.",
    "blog.a2_proTip": "Ultra-glossy mirror topcoats bring out the multidimensional depth of dark autumnal shades.",
    "blog.a3_title": "Cuticle Oil: Why it is your ultimate daily essential",
    "blog.a3_excerpt": "Hydration is the secret to enduring manicures. Discover why nourishing cuticle oil is a non-negotiable daily step.",
    "blog.a3_category": "Hand Skincare",
    "blog.a3_date": "August 20, 2026",
    "blog.a3_intro": "Often overlooked, cuticle oil is actually the single most important secret for velvety soft, healthy hands that look freshly manicured weeks later.",
    "blog.a3_h1": "Deep Cellular Nourishment",
    "blog.a3_t1": "Unlike hand creams that only sit on the surface, pure botanical oils (such as jojoba, sweet almond, and vitamin E) penetrate the nail matrix to stimulate resilient growth.",
    "blog.a3_h2": "Hangnail & Dryness Prevention",
    "blog.a3_t2": "Consistent application softens surrounding skin, preventing painful hangnails, micro-tears, and dry cracked edges.",
    "blog.a3_h3": "Extended Polish Flexibility",
    "blog.a3_t3": "A supple, hydrated nail absorbs physical impacts better, creating a flexible and resilient foundation that prevents gel lifting.",
    "blog.a3_conclusion": "Just 30 seconds a day will fundamentally transform the vitality and appearance of your hands.",
    "blog.a3_proTip": "Massage the oil in gentle circular motions over the entire cuticle contour down to the first knuckle to stimulate blood circulation.",
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Have questions or curious about our treatments? Here are clear, detailed answers to our most common inquiries.",
    "faq.q1": "How long does semi-permanent gel polish last?",
    "faq.a1": "Standard semi-permanent polish typically lasts 2 to 3 weeks. When choosing a structured rubber-base reinforced manicure, longevity extends up to 4 full weeks with remarkable strength, high-gloss shine, and natural nail protection.",
    "faq.q2": "How can I safely remove gel polish or nail extensions?",
    "faq.a2": "It is essential never to peel, bite, or scrape off gel products yourself, as this can thin and damage your natural nail layers. We provide gentle professional removal using calibrated precision bits that preserve your nail health.",
    "faq.q3": "What hygiene and sterilization standards do you follow?",
    "faq.a3": "Safety and impeccable hygiene are our highest priorities. We use single-use files and buffers for every client. All surgical-grade stainless steel instruments are thoroughly cleaned, disinfected, and sterilized in a medical autoclave in individually sealed pouches.",
    "faq.q4": "What is your cancellation or late arrival policy?",
    "faq.a4": "We kindly ask for at least 24 hours notice for any cancellation or rescheduling to allow us to accommodate other clients. In the event of an arrival delayed by more than 15 minutes, treatments may need to be adjusted to honor subsequent appointments.",
    "faq.q5": "Does nail reconstruction damage natural nails?",
    "faq.a5": "Absolutely not. When performed properly by a certified technician using premium European-certified products, reconstruction does not harm the natural nail. In fact, it provides structural protection and is ideal for overcoming nail-biting habits.",
    "faq.q6": "Can I bring a reference photo for custom Nail Art?",
    "faq.a6": "Of course! You can share your inspiration photo directly via WhatsApp prior to your appointment or show it during consultation. We create hand-painted bespoke designs, delicate babyboomers, refined French tips, and crystal embellishments.",
    "book.title": "Book Your Treatment",
    "book.subtitle": "Complete the form below to request your appointment. You will receive prompt confirmation via WhatsApp.",
    "book.progress": "Form completion",
    "book.step1": "1. Select Treatment",
    "book.selectServicePlaceholder": "-- Choose a Treatment --",
    "book.step2": "2. Preferred Date & Time",
    "book.dateLabel": "Preferred Date",
    "book.timeLabel": "Time Window",
    "book.selectTimePlaceholder": "-- Choose time slot --",
    "book.timeMorning": "Morning (09:30 - 13:00)",
    "book.timeAfternoon": "Afternoon (14:30 - 19:30)",
    "book.step3": "3. Your Contact Details",
    "book.firstName": "First Name",
    "book.lastName": "Last Name",
    "book.email": "Email Address",
    "book.phone": "Mobile (WhatsApp)",
    "book.notes": "Notes or Special Requests (optional)",
    "book.notesPlaceholder": "E.g. 'I would like custom nail art', 'I have fragile nails', etc.",
    "book.step4": "4. Additional Options",
    "book.optWhatsapp": "I wish to receive an automatic appointment reminder on WhatsApp.",
    "book.optRemoval": "I currently have gel/polish from another salon that needs removal (+15 min).",
    "book.submitBtn": "Send Booking Request",
    "book.badge1Title": "Fast Confirmation",
    "book.badge1Desc": "Direct response and confirmation on WhatsApp within hours.",
    "book.badge2Title": "Certified Hygiene",
    "book.badge2Desc": "Autoclave sterilized tools and single-use files.",
    "book.badge3Title": "Exclusive Studio",
    "book.badge3Desc": "Intimate, welcoming studio in Milan City-Life.",
    "book.successTitle": "Request Received Successfully!",
    "book.successDesc": "Thank you for choosing BeautyDreamer. We have logged your request and will contact you shortly on WhatsApp for final confirmation.",
    "book.summaryTitle": "Appointment Request Summary:",
    "book.summaryTreatment": "Treatment:",
    "book.summaryDate": "Date:",
    "book.summaryTime": "Time Slot:",
    "book.summaryClient": "Client:",
    "book.summaryPhone": "Phone:",
    "book.summaryLocation": "Location:",
    "book.addToGoogleCal": "Add to Google Calendar",
    "book.downloadIcs": "Download Reminder (.ics / Apple)",
    "book.shareWhatsApp": "Send Reminder on WhatsApp",
    "book.backHome": "Back to Home",
    "footer.tagline": "A luxury beauty experience to elevate your femininity.",
    "footer.quickLinks": "Quick Links",
    "footer.contacts": "Contact Us",
    "footer.legalInfo": "Legal Information",
    "footer.rights": "All rights reserved.",
    "services.promoBannerTitle": "Special Offers, Combos & Gift Cards",
    "services.promoBannerSubtitle": "Take advantage of active promotions, combine multiple treatments to unlock exclusive bundle discounts, or use voucher codes and gift cards for your luxury beauty appointment.",
    "services.copyCode": "Copy Code",
    "services.copiedCode": "Copied!",
    "services.bookWithPromo": "Book with this Promo",
    "services.p_dry_badge": "COMBO PROMO -15%",
    "services.p_dry_title": "Perfect Hands & Feet Combo",
    "services.p_dry_desc": "Combine with Bladeless Pedicure and get 15% off the total + complimentary cuticle hydration treatment.",
    "services.p_dry_code": "COMBOMANIPIEDI",
    "services.p_semi_badge": "3-SESSION PROMO PACK",
    "services.p_semi_title": "Gel Polish Beauty Pass",
    "services.p_semi_desc": "3-session pack with 1 complimentary bespoke Nail Art included per session. Save instantly with this voucher.",
    "services.p_semi_code": "SEMIPACK",
    "services.p_ricostruzione_badge": "10% OFF VOUCHER",
    "services.p_ricostruzione_title": "Welcome Promo Reconstruction",
    "services.p_ricostruzione_desc": "10% off your first full nail reconstruction set (Gel, Acrygel, or Acrylic).",
    "services.p_ricostruzione_code": "NEWBEAUTY",
    "services.p_spa_badge": "GIFT CARD & VOUCHER",
    "services.p_spa_title": "Spa Ritual or Luxury Gift Card",
    "services.p_spa_desc": "Gift or treat yourself to a ritual of deep beauty and relaxation. Also available as a luxury Gift Card.",
    "services.p_spa_code": "GIFTDREAM",
    "services.p_callus_badge": "WELLNESS COMBO",
    "services.p_callus_title": "Smoothing Combo + Spa Pedicure",
    "services.p_callus_desc": "Combine Calluspeeling and Spa Pedicure for only €55 (instead of €65) for completely regenerated feet.",
    "services.p_callus_code": "PEDISPA55",
    "book.voucherLabel": "Promo Code, Voucher or Gift Card (Optional)",
    "book.voucherPlaceholder": "E.g. COMBOMANIPIEDI, BEAUTY10, SEMIPACK...",
    "book.voucherApply": "Apply",
    "book.voucherApplied": "Promo successfully applied!",
    "book.voucherInvalid": "Invalid or expired promo code",
    "book.summaryVoucher": "Voucher / Promo:"
  },
  "es": {
    "nav.home": "Inicio",
    "nav.about": "Sobre Mí",
    "nav.services": "Servicios",
    "nav.portfolio": "Antes y Después",
    "nav.blog": "Blog",
    "nav.faq": "Preguntas Frecuentes",
    "nav.bookNow": "Reserva Ahora",
    "nav.selectLang": "Seleccionar Idioma",
    "nav.lang_it": "Italiano",
    "nav.lang_en": "English",
    "nav.lang_es": "Español",
    "hero.loading": "Cargando experiencia...",
    "hero.title1": "El arte de la manicura",
    "hero.title2": "a tu medida",
    "hero.desc": "Una experiencia de belleza para realzar tu feminidad. Cada detalle está diseñado para crear armonía, elegancia y personalidad única.",
    "hero.bookBtn": "Reserva Ahora",
    "hero.servicesBtn": "Descubre los Servicios",
    "intro.badge": "Sobre Nosotros",
    "intro.heading": "Un ambiente íntimo y refinado",
    "intro.p1": "Aquí no es solo una cita: es un momento de relajación y bienestar dedicado exclusivamente a ti. Beauty Dreamer nace de la idea de ofrecer un nuevo concepto de cuidado de uñas: no solo estética, sino realzar la belleza natural de cada persona.",
    "intro.p2": "Porque unas manos cuidadas no son solo un detalle, sino un sello distintivo de elegancia.",
    "intro.myStory": "Mi historia",
    "vieni.title": "Ven a",
    "vieni.titleAccent": "visitarnos",
    "vieni.desc": "Ven a visitarnos, atendemos en Milán City-Life. Un ambiente diseñado para que te relajes, donde el cuidado personal se transforma en un ritual de belleza.",
    "vieni.cta": "Reserva una cita",
    "srvPrev.badge": "Nuestros Tratamientos",
    "srvPrev.heading": "Cuida de ti",
    "srvPrev.manicureTitle": "Manicura y Pedicura",
    "srvPrev.manicureDesc": "Tratamientos curativos en seco o rituales spa para manos y pies impecables.",
    "srvPrev.ricostruzioneTitle": "Reconstrucción",
    "srvPrev.ricostruzioneDesc": "Gel, Acrygel o Acrílico para extensiones naturales o diseños audaces.",
    "srvPrev.nailArtTitle": "Nail Art",
    "srvPrev.nailArtDesc": "Desde manicura francesa hasta babyboomer, detalles artísticos a mano alzada.",
    "srvPrev.allServicesBtn": "Ver Lista Completa de Precios",
    "testimonials.quote": "Con años de experiencia en el sector de la belleza y una pasión innata por la excelencia, Chiara te acogerá en un ambiente exclusivo y refinado, donde tu bienestar y belleza son lo primordial.",
    "testimonials.author": "Nuestras Clientas",
    "ig.openTitle": "¿Abrir Instagram?",
    "ig.openDesc": "¿Deseas ver el perfil oficial de @beautydreameraesthetic para descubrir todas las creaciones y novedades?",
    "ig.openBtn": "Abrir Perfil",
    "ig.stayBtn": "Permanecer en el Sitio",
    "ig.follow": "Seguir",
    "ig.caption": "El arte de la manicura en Milán City-Life. Dedicación, elegancia y cuidado en cada detalle ✨💅",
    "ig.audio": "Audio original • Chiara Lulli • Beauty Dreamer",
    "ig.soundOn": "Activar Sonido",
    "ig.soundOff": "Silenciar Sonido",
    "about.badge": "Mi Historia",
    "about.p1": "Me llamo Chiara, esteticista especializada y técnica profesional de uñas.",
    "about.p2": "Desde muy pequeña desarrollé una profunda pasión por la estética. Cautivada por el maquillaje, los esmaltes y las manos impecables, decidí emprender mi camino hacia lo que siempre fue mi gran vocación.",
    "about.p3": "Me capacité intensamente en estética integral, maquillaje profesional y esculpido de uñas, asistiendo a cursos de perfeccionamiento en reconstrucción estructural. Hoy he alcanzado mi meta, convirtiendo lo que siempre soñé en una entrega diaria de excelencia.",
    "about.quote": "Dedicación y amor son los dos pilares esenciales que hacen único mi trabajo, gratificándome cada día más.",
    "about.cta": "Descubre mis servicios",
    "about.welcomeBadge": "Bienvenidos a",
    "about.welcomeHeading": "Beauty Dreamer",
    "about.welcomeP1": "El refugio perfecto para el arte de la manicura y pedicura, atendido personalmente por Chiara Lulli. En nuestro Nail Concept, nos dedicamos a ofrecer tratamientos personalizados que se adaptan a las necesidades de cada clienta.",
    "about.welcomeP2": "Nuestra misión es hacer de cada visita una experiencia profundamente relajante, regeneradora y sobre todo hermosa.",
    "about.welcomeP3": "Elige Beauty Dreamer para tu próximo tratamiento y déjate envolver por un universo de color y elegancia atemporal.",
    "services.headerTitle": "Nuestros Tratamientos",
    "services.headerSubtitle": "Descubre la lista completa de servicios ofrecidos por BeautyDreamer. Reserva tu momento de relajación.",
    "services.bookService": "Reserva este servicio",
    "services.cat1": "Manicura y Pedicura",
    "services.s1_1_title": "Dry Manicure (Rusa)",
    "services.s1_1_desc": "Tratamiento en seco con torno para un acabado de cutículas perfecto y máxima adherencia del producto.",
    "services.s1_1_price": "desde 20€",
    "services.s1_2_title": "Pedicura Sin Cuchillas",
    "services.s1_2_desc": "Pedicura estética y curativa realizada con instrumental seguro y máxima delicadeza sin cuchillas.",
    "services.s1_2_price": "desde 35€",
    "services.cat2": "Esmaltado Semipermanente",
    "services.s2_1_title": "Manos o Pies",
    "services.s2_1_desc": "Semipermanente clásico o con nivelación rubber para mayor durabilidad y brillo.",
    "services.s2_1_price": "desde 30€",
    "services.cat3": "Reconstrucción y Relleno",
    "services.s3_1_title": "Reconstrucción Gel / Acrygel / Acrílico",
    "services.s3_1_desc": "Longitud corta, media, larga, extrema o corrección de onicofagia (uñas mordidas).",
    "services.s3_1_price": "desde 60€",
    "services.s3_2_title": "Relleno Gel / Acrygel / Acrílico",
    "services.s3_2_desc": "Mantenimiento mensual cada 3 o 4 semanas.",
    "services.s3_2_price": "desde 45€",
    "services.s3_3_title": "Nivelación sobre Uña Natural",
    "services.s3_3_desc": "Refuerzo aplicado sobre la uña natural con Gel, Acrygel o Acrílico.",
    "services.s3_3_price": "desde 45€",
    "services.cat4": "Nail Art",
    "services.s4_1_title": "Adicional al tratamiento",
    "services.s4_1_desc": "Francesa dibujada, babyboomer, diseños personalizados, cristales Swarovski, pigmentos cromados.",
    "services.s4_1_price": "desde 5€",
    "services.cat5": "Tratamientos para Manos y Pies",
    "services.s5_1_title": "Gel Break",
    "services.s5_1_desc": "Tratamiento restaurador y fortalecedor para uñas debilitadas.",
    "services.s5_1_price": "desde 15€",
    "services.s5_2_title": "Anti Dark Spot",
    "services.s5_2_desc": "Tratamiento antimanchas e iluminador para el dorso de las manos.",
    "services.s5_2_price": "desde 20€",
    "services.s5_3_title": "Manicura / Pedicura Spa",
    "services.s5_3_desc": "Exfoliación profunda, mascarilla ultrahidratante y masaje relajante.",
    "services.s5_3_price": "desde 30€",
    "services.s5_4_title": "Calluspeeling",
    "services.s5_4_desc": "Tratamiento exfoliante y suavizante específico para durezas y callosidades.",
    "services.s5_4_price": "desde 35€",
    "services.cat6": "Depilación Suave",
    "services.s6_1_title": "Cera Sin Bandas (Mujer/Hombre)",
    "services.s6_1_desc": "Depilación tibia ultrasuave especialmente formulada para pieles sensibles.",
    "services.s6_1_price": "desde 10€",
    "portfolio.title": "Antes y Después",
    "portfolio.subtitle": "Descubre las transformaciones de nuestros tratamientos. Galería exclusiva de Chiara Lulli.",
    "portfolio.tabAll": "Todos",
    "portfolio.tabRicostruzione": "Reconstrucción",
    "portfolio.tabNailArt": "Nail Art",
    "portfolio.tabPrimaDopo": "Antes y Después",
    "portfolio.bookResult": "Reserva este resultado",
    "portfolio.swipeTip": "Desliza o haz clic en las flechas para ver los vídeos",
    "blog.title": "Blog y Secretos de Belleza",
    "blog.subtitle": "Guías, artículos y consejos profesionales para el cuidado y salud de tus uñas, por Chiara Lulli.",
    "blog.allArticles": "Todos los Artículos",
    "blog.readTime": "tiempo de lectura",
    "blog.readArticle": "Leer Artículo Completo",
    "blog.readingModalTitle": "Lectura Exclusiva",
    "blog.authorBy": "Por Chiara Lulli",
    "blog.proTipTitle": "El Consejo Pro de Chiara",
    "blog.shareWhatsApp": "Compartir en WhatsApp",
    "blog.bookAfterReading": "Reservar Tratamiento",
    "blog.backToBlog": "Volver al Blog",
    "blog.a1_title": "Cómo mantener el esmalte semipermanente perfecto por más tiempo",
    "blog.a1_excerpt": "Pequeños secretos diarios y hábitos a evitar para que tu manicura dure hasta 4 semanas impecable.",
    "blog.a1_category": "Cuidado de Uñas",
    "blog.a1_date": "10 de Septiembre 2026",
    "blog.a1_intro": "El esmalte semipermanente es la solución perfecta para lucir uñas brillantes e intactas durante semanas. Sin embargo, su durabilidad depende también de tu rutina de cuidado en casa. Estos son los consejos expertos de Chiara para maximizar la fijación de tu manicura.",
    "blog.a1_h1": "1. Protege tus manos con guantes",
    "blog.a1_t1": "Los detergentes, desengrasantes y productos químicos pueden degradar el top coat brillante y causar levantamientos tempranos. Usa siempre guantes al fregar o limpiar.",
    "blog.a1_h2": "2. Hidratación diaria de cutículas",
    "blog.a1_t2": "Aplicar una gota de aceite nutritivo cada noche mantiene la lámina ungueal flexible, previniendo roturas y conservando las cutículas como recién salidas del salón.",
    "blog.a1_h3": "3. No uses tus uñas como herramientas",
    "blog.a1_t3": "Evita hacer palanca para abrir latas o rascar superficies duras: los microimpactos repetidos generan fisuras invisibles que terminan en desprendimientos.",
    "blog.a1_conclusion": "Siguiendo estos simples cuidados, tu esmaltado se mantendrá reluciente hasta tu próxima cita.",
    "blog.a1_proTip": "Si notas un pequeño levantamiento en el borde, nunca lo arranques: agenda un retoque rápido para no dañar las capas de la uña natural.",
    "blog.a2_title": "Tendencias de Nail Art Otoño / Invierno",
    "blog.a2_excerpt": "Descubre los colores y acabados de moda: desde tonos burdeos intensos y cherry mocha hasta el minimalismo chic.",
    "blog.a2_category": "Tendencias y Estilo",
    "blog.a2_date": "2 de Septiembre 2026",
    "blog.a2_intro": "La nueva temporada celebra la elegancia sofisticada con detalles de alta costura. Entre tonalidades cálidas y destellos luminosos, tus manos son el mejor accesorio.",
    "blog.a2_h1": "Burdeos Profundo y Cherry Mocha",
    "blog.a2_t1": "Los tonos vino, ciruela y cereza oscura dominan las peticiones: clásicos, atemporales y favorecedores tanto en uñas cortas como almendradas.",
    "blog.a2_h2": "Micro Francesa y Toques Dorados",
    "blog.a2_t2": "La clásica manicura francesa se reinventa con trazos ultrafinos y toques de polvo cromado o dorado sobre bases nude traslúcidas.",
    "blog.a2_h3": "Efecto Cristal y Babyboomer Soft",
    "blog.a2_t3": "La suave transición degradé del blanco lechoso al rosa porcelana brinda un aspecto limpio, pulcro y sofisticado ideal para cualquier ocasión.",
    "blog.a2_conclusion": "Ven a visitarnos en Milán City-Life para personalizar tu Nail Art según la forma natural de tus manos.",
    "blog.a2_proTip": "Los acabados extrabrillantes tipo espejo resaltan al máximo la riqueza de los tonos oscuros de otoño.",
    "blog.a3_title": "Aceite de Cutículas: Por qué no puede faltar en tu rutina",
    "blog.a3_excerpt": "La hidratación es la clave para una manicura duradera. Descubre por qué el aceite de cutículas es tu mejor aliado.",
    "blog.a3_category": "Cuidado de Manos",
    "blog.a3_date": "20 de Agosto 2026",
    "blog.a3_intro": "A menudo olvidado, el aceite para cutículas es en realidad el secreto número uno para lucir manos suaves, saludables e impecables todos los días.",
    "blog.a3_h1": "Nutrición en Profundidad",
    "blog.a3_t1": "A diferencia de las cremas de manos convencionales, los aceites botánicos puros (como jojoba, almendras dulces y vitamina E) penetran en la matriz de la uña estimulando un crecimiento fuerte.",
    "blog.a3_h2": "Prevención de Padrastros y Resequedad",
    "blog.a3_t2": "Su uso regular flexibiliza la piel del contorno, evitando que se formen padrastros dolorosos, cortes o descamaciones.",
    "blog.a3_h3": "Mayor Flexibilidad del Esmalte",
    "blog.a3_t3": "Una uña hidratada amortigua los golpes con elasticidad, creando una base estable y duradera para el gel y el semipermanente.",
    "blog.a3_conclusion": "Solo 30 segundos al día bastan para transformar radicalmente la belleza de tus manos.",
    "blog.a3_proTip": "Masajea el aceite con movimientos circulares por toda la cutícula y hasta la primera falange para reactivar la microcirculación.",
    "faq.title": "Preguntas Frecuentes",
    "faq.subtitle": "¿Tienes dudas sobre los tratamientos? Aquí encontrarás respuestas claras y detalladas a las consultas más habituales.",
    "faq.q1": "¿Cuánto dura el esmalte semipermanente?",
    "faq.a1": "El semipermanente clásico tiene una duración media de 2 a 3 semanas. Al optar por un semipermanente con nivelación rubber o base estructurada, la duración se extiende hasta 4 semanas completas con alta resistencia y brillo impecable.",
    "faq.q2": "¿Cómo puedo retirar el semipermanente o la reconstrucción de forma segura?",
    "faq.a2": "Es fundamental no arrancar ni raspar el producto en casa, para no debilitar ni adelgazar la lámina ungueal. Ofrecemos un servicio de retirada profesional con fresas calibradas que cuida la salud de tus uñas.",
    "faq.q3": "¿Qué normas de higiene y esterilización cumplen?",
    "faq.a3": "La seguridad y la higiene son nuestra máxima prioridad. Utilizamos limas y material desechable para cada clienta. Todo el instrumental de acero quirúrgico es rigurosamente desinfectado y esterilizado en autoclave en bolsas selladas individuales.",
    "faq.q4": "¿Cuál es la política de cancelación o retraso?",
    "faq.a4": "Te solicitamos avisar con al menos 24 horas de antelación en caso de necesitar cancelar o modificar tu cita. Ante retrasos superiores a 15 minutos, el servicio podría adaptarse para no perjudicar a las siguientes clientas.",
    "faq.q5": "¿La reconstrucción daña la uña natural?",
    "faq.a5": "En absoluto. Realizada por una profesional cualificada con productos europeos de alta gama, la reconstrucción no perjudica la uña. Al contrario, la protege de impactos y es una excelente solución para superar la onicofagia (uñas mordidas).",
    "faq.q6": "¿Puedo traer una foto de referencia para el Nail Art?",
    "faq.a6": "¡Por supuesto! Puedes enviarnos tu imagen de inspiración por WhatsApp antes de tu cita o mostrarla en cabina. Diseñamos decoraciones a mano alzada, babyboomer, francesas refinadas e incrustaciones de pedrería.",
    "book.title": "Reserva tu Tratamiento",
    "book.subtitle": "Completa el formulario para solicitar tu cita. Recibirás una confirmación rápida por WhatsApp.",
    "book.progress": "Progreso del formulario",
    "book.step1": "1. Selecciona el Tratamiento",
    "book.selectServicePlaceholder": "-- Elige un Tratamiento --",
    "book.step2": "2. Fecha y Horario Deseados",
    "book.dateLabel": "Fecha Preferida",
    "book.timeLabel": "Franja Horaria",
    "book.selectTimePlaceholder": "-- Elige franja horaria --",
    "book.timeMorning": "Mañana (09:30 - 13:00)",
    "book.timeAfternoon": "Tarde (14:30 - 19:30)",
    "book.step3": "3. Tus Datos de Contacto",
    "book.firstName": "Nombre",
    "book.lastName": "Apellidos",
    "book.email": "Correo Electrónico",
    "book.phone": "Teléfono Móvil (WhatsApp)",
    "book.notes": "Notas o Peticiones Especiales (opcional)",
    "book.notesPlaceholder": "Ej. 'Deseo un nail art personalizado', 'Tengo uñas frágiles', etc.",
    "book.step4": "4. Opciones Adicionales",
    "book.optWhatsapp": "Deseo recibir el recordatorio automático de la cita por WhatsApp.",
    "book.optRemoval": "Tengo esmalte/gel previo de otro salón que requiere retirada (+15 min).",
    "book.submitBtn": "Enviar Solicitud de Reserva",
    "book.badge1Title": "Confirmación Rápida",
    "book.badge1Desc": "Respuesta y confirmación por WhatsApp en pocas horas.",
    "book.badge2Title": "Higiene Certificada",
    "book.badge2Desc": "Herramientas esterilizadas en autoclave y material desechable.",
    "book.badge3Title": "Estudio Exclusivo",
    "book.badge3Desc": "Ambiente acogedor y privado en Milán City-Life.",
    "book.successTitle": "¡Solicitud Recibida con Éxito!",
    "book.successDesc": "Gracias por elegir BeautyDreamer. Hemos registrado tu solicitud y nos pondremos en contacto contigo por WhatsApp para la confirmación definitiva.",
    "book.summaryTitle": "Resumen de tu solicitud:",
    "book.summaryTreatment": "Tratamiento:",
    "book.summaryDate": "Fecha:",
    "book.summaryTime": "Horario:",
    "book.summaryClient": "Cliente:",
    "book.summaryPhone": "Teléfono:",
    "book.summaryLocation": "Ubicación:",
    "book.addToGoogleCal": "Añadir a Google Calendar",
    "book.downloadIcs": "Descargar Recordatorio (.ics / Apple)",
    "book.shareWhatsApp": "Enviar Recordatorio por WhatsApp",
    "book.backHome": "Volver al Inicio",
    "footer.tagline": "Una experiencia de belleza para realzar tu feminidad.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.contacts": "Contacto",
    "footer.legalInfo": "Información Legal",
    "footer.rights": "Todos los derechos reservados.",
    "services.promoBannerTitle": "Ofertas Especiales, Combos y Gift Cards",
    "services.promoBannerSubtitle": "Aprovecha las promociones activas, combina múltiples tratamientos para desbloquear descuentos exclusivos o utiliza cupones y gift cards para tu momento de belleza.",
    "services.copyCode": "Copiar Código",
    "services.copiedCode": "¡Copiado!",
    "services.bookWithPromo": "Reservar con esta Promo",
    "services.p_dry_badge": "COMBO PROMO -15%",
    "services.p_dry_title": "Combo Manos y Pies Perfectos",
    "services.p_dry_desc": "Combina con Pedicura Sin Cuchillas y obtén un 15% de descuento en el total + hidratación de cutículas de regalo.",
    "services.p_dry_code": "COMBOMANIPIEDI",
    "services.p_semi_badge": "PACK 3 SESIONES PROMO",
    "services.p_semi_title": "Bono Belleza Semipermanente",
    "services.p_semi_desc": "Bono de 3 sesiones con 1 Nail Art de regalo incluida por cada sesión. Ahorra al instante con este cupón.",
    "services.p_semi_code": "SEMIPACK",
    "services.p_ricostruzione_badge": "CUPÓN -10%",
    "services.p_ricostruzione_title": "Welcome Promo Reconstrucción",
    "services.p_ricostruzione_desc": "10% de descuento reservado en tu primera reconstrucción completa (Gel, Acrygel o Acrílico).",
    "services.p_ricostruzione_code": "NEWBEAUTY",
    "services.p_spa_badge": "GIFT CARD Y CUPÓN",
    "services.p_spa_title": "Experiencia Spa o Gift Card de Regalo",
    "services.p_spa_desc": "Regala o regálate un ritual de belleza y relajación profunda. Disponible también como elegante Gift Card.",
    "services.p_spa_code": "GIFTDREAM",
    "services.p_callus_badge": "COMBO WELLNESS",
    "services.p_callus_title": "Combo Alisado + Pedicura Spa",
    "services.p_callus_desc": "Combina Calluspeeling y Pedicura Spa por solo 55€ (en lugar de 65€) para pies totalmente regenerados.",
    "services.p_callus_code": "PEDISPA55",
    "book.voucherLabel": "Código de Cupón, Promo o Gift Card (Opcional)",
    "book.voucherPlaceholder": "Ej. COMBOMANIPIEDI, BEAUTY10, SEMIPACK...",
    "book.voucherApply": "Aplicar",
    "book.voucherApplied": "¡Promo aplicada con éxito!",
    "book.voucherInvalid": "Código no válido o caducado",
    "book.summaryVoucher": "Cupón / Promo:"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("it");

  useEffect(() => {
    const saved = localStorage.getItem("beautydreamer_lang") as Language;
    if (saved && (saved === "it" || saved === "en" || saved === "es")) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("beautydreamer_lang", lang);
  };

  const t = (key: string): string => {
    const langDict = (translations as any)[language];
    if (langDict && key in langDict) {
      return langDict[key];
    }
    // Fallback to Italian
    if (translations.it && (translations.it as any)[key]) {
      return (translations.it as any)[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
